services:
  - type: web
    name: plivo-status
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    healthCheckPath: /health
    disk:
      name: plivo-status-data
      mountPath: /var/www/html/database
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: "Plivo Status"
      - key: APP_URL
        value: https://plivo-status.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_DRIVER
        value: pusher
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_APP_KEY
        sync: false
      - key: PUSHER_APP_SECRET
        sync: false
      - key: PUSHER_HOST
        value: api-mt1.pusherapp.com
      - key: PUSHER_PORT
        value: 443
      - key: PUSHER_SCHEME
        value: https
      - key: PUSHER_APP_CLUSTER
        sync: false
      - key: VITE_PUSHER_APP_KEY
        sync: false
      - key: VITE_PUSHER_APP_CLUSTER
        sync: false

disks:
  - name: plivo-status-data
    sizeGB: 1 